# Generated by Django 3.2.7 on 2021-09-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_alter_books_bookphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='bookPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='books_Img/'),
        ),
    ]
