# Generated by Django 3.2.7 on 2021-09-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('bookPhoto', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
    ]
